# Generated by Django 5.1.2 on 2024-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atelier360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Traité', 'Traité'), ('Rejeté', 'Rejeté')], default='En attente', max_length=20),
        ),
    ]
