# Generated by Django 5.1.2 on 2024-11-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atelier360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
