# Generated by Django 5.1.2 on 2024-11-01 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atelier360', '0002_alter_utilisateur_is_superuser'),
        ('Atelier360', '0002_rename_categorie_article_categorie'),
    ]

    operations = [
    ]
